[project]

name = "dupe"
version = "0.1.0"
description = "Finds duplicate files"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Damon Allison", email = "damon@damonallison.com" }]
dependencies = []


[dependency-groups]
dev = ["black>=25.1.0", "pytest>=8.4.0"]
